### ISSUE TITLE
luaD_pcall函数存在中存在内存泄露

### ISSUE THREAD

**Issue by txkgithub** [Manistein/dummylua-tutorial#10]
while(free_ci) {
            if (free_ci == old_ci) {
                free_ci = free_ci->next;
                continue;
            }

            struct CallInfo* previous = free_ci->previous;
            previous->next = NULL;
            
            struct CallInfo* next = free_ci->next;
            (*g->frealloc)(g->ud, free_ci, sizeof(struct CallInfo), 0);
            free_ci = next;
        }
在第二次迭代时，free_ci 的previous已经被释放了，那么执行到    struct CallInfo* previous = free_ci->previous;时，此时的previous已经成为野指针。

**Comment by Manistein** [comment]
这个部分从part02实现GC开始就被删除掉了。另外，许多本项目存在的bug，基本在https://github.com/Manistein/let-us-build-a-lua-interpreter 这个仓库修复。感谢反馈。

**Comment by Manistein** [comment]
这个部分从part02实现GC开始就被删除掉了。另外，许多本项目存在的bug，基本在https://github.com/Manistein/let-us-build-a-lua-interpreter 这个仓库修复。感谢反馈。
