### ISSUE TITLE
剩下的章节还会补完吗

### ISSUE THREAD

**Issue by yue-qiu** [Manistein/dummylua-tutorial#3]
因为工作原因开始接触 Lua 不久，看了楼主的文章感到很受用。看到 README 里还有几篇文章是灰的，想问下楼主还有计划继续更新吗，万分期待

**Comment by Manistein** [comment]
会的，目前已经和出版社签约，所有内容会重新整理，编入我的新书《Lua解释器构建：从虚拟机到编译器》中。
