### ISSUE TITLE
part6 错别字

### ISSUE THREAD

**Issue by ping003** [Manistein/dummylua-tutorial#6]
>从上面的伪代码我们可以看到，词法分析器识别一个token，需要不断从源码文件中，一个一个读取字符，然后判断它可能是哪种类型的token，最后作相应的处理，比如readstring和readnumber操作，就是把有效字符串识和数值别出来，最后存储在LexState结构的Token类型变量t中。readstring函数和readnumber函数内部也会多次调用zget函数，不断获取新的字符，最后生成token。

**就是把有效字符串识和数值别出来**->就是把有效字符串和数值识别出来

**Comment by Manistein** [comment]
已修正。
