### ISSUE TITLE
part7 描述错误

### ISSUE THREAD

**Issue by ping003** [Manistein/dummylua-tutorial#7]
>OP_TEST if not (R(A) <=> C) then pc++
如果寄存器A的值，与C值相等，那么PC寄存器自增1(跳过下一个指令)，通常TEST指令后面必定要跟一个JUMP指令

应该是如果寄存器A的值不等于C值，那么PC寄存器自增1(跳过下一个指令)，通常TEST指令后面必定要跟一个JUMP指令

**Comment by Manistein** [comment]
已修正。
